accounts/urls.py
from django.urls import path
from .import views
app_name ='accounts'
urlpatterns = [

    path('login/',views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
path('logout/', views.logout_view, name='logout'),

  ]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view, name='home'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
  ]

#UPLOAD EDİLECEK DOSYALARIN URL TANIMLAMASI
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
 

post/urls.py
from django.urls import path
from .import views
app_name ='post'
urlpatterns = [

    path('index/',views.post_index, name='index'),
    path('create/',views.post_create, name='create'),
    path('<slug>/',views.post_detail, name='detail'),
    path('<slug>/update/',views.post_update, name='update'),
    path('<slug>/delete/',views.post_delete, name='delete'),

  ]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render,HttpResponse


def home_view(request):
	if request.user.is_authenticated:
		context={
			'isim': 'Sena',
		}
	else:
		context={
			'isim': 'Misafir',
		}
	return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
		<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %} Django Lectures {% endblock %}</title>

</head>
<body>

	{% include 'header.html' %}

	{% include 'messages.html' %}

	{% block body %}

	{% endblock %}
	
	<main>
    {% block content %}
    {% endblock %}
  	</main>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Add New Content</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Home Page</a></li>
                <li><a href="{% url 'post:index' %}">View Posts</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>


                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home - {{ block.super }}{% endblock %}

{% block body %}
	
    <div class="container-fluid">
       <!-- <div class="row" style="margin-botton:30px;">

            &lt;!&ndash;<div class="col-md-3 col-sm-6 " style="background-color: purple; height:100px;">ürün1</div>
            <div class="col-md-3 col-sm-6" style="background-color: blue; height:100px;">ürün2</div>
            <div class="col-md-3 col-sm-6" style="background-color: orange; height:100px;">ürün3</div>
            <div class="col-md-3 col-sm-6" style="background-color: pink; height:100px;">ürün4</div>&ndash;&gt;

        </div>-->
        <div class="row">
            <div class="col-md-4" style="background-color:red; height:100px;"></div>
            <div class="col-md-8" style="background-color:black; height:100px;">
                <div class="row">
                <div class="col-md-2" style="background-color:blue; height: 100px;"></div>
                <div class="col-md-6" style="background-color:purple; height: 100px;"></div>
                <div class="col-md-4" style="background-color:orange; height: 100px;"></div>
                </div>
            </div>
        </div>
        Welcome, {{ request.user.get_full_name }}
    </div>

{% endblock %}

templates/messages.html
	{% if messages %}

    	{% for message in messages %}
    		<div class="alert alert-success alert-dismissible " role="alert">
  				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
 				 </button>
				{{ message }}
			</div>



    {% endfor %}

	{% endif %}